### ISSUE TITLE
ServoStatus publisher

### ISSUE THREAD

**Issue by czogran** [GroupOfRobots/MiniRysRQT#2]
Adding servo_status to control panel and joystick panel

**Comment by czogran** [comment]
![Uploading Screenshot from 2023-10-31 14-16-28.png…]()

**Comment by czogran** [comment]
![image](https://github.com/GroupOfRobots/MiniRysRQT/assets/26524922/1bce8f49-9aef-48b2-a3e3-16d676e5a3fc)

**Comment by czogran** [comment]
commit:
0db78f18aaf6c632f97b23bfec4d283835abb03d -> joystick and extracting shared part with control panel
94441634594c460c5db601d9970c140f4ac0cfd8 -> control panel

**Comment by czogran** [comment]
@Kubaless please verify :)

**Comment by Kubaless** [comment]
it works. good job 👍
